import "./globals.css";
import { ToastContainer, toast } from 'react-toastify';
import AosInt from "@/utils/aos";
import Navbar from "@/components/modules/navbar/Navbar";
import { authUser } from "@/utils/serverHelpers";
import ScrollToTop from "@/utils/scrollToTop";
import { CartProvider } from "@/context/Cartcontex";
import connectToDB from "@/configs/db";
import wishlistModel from '@/models/wishlist'
import { usePathname } from "next/navigation";

export const metadata = {
  title: "فروشگاه مواد غذایی- بوتونیکا",
  description: "Generated by arefe salehi",
  icons: {
    icon: '/images/image.png',
    shortcut: '/images/image.png',
    apple: '/images/image.png',
  },
};

export default async function RootLayout({ children }) {

  const user = await authUser()
  console.log('user homepage=>', user);


  let wishes = []
  connectToDB()


  console.log('wishlist User=>', user)
  if (user) {
    wishes = await wishlistModel
      .find({ user: user._id })
      .populate('product', ' name ')
      .lean()

  }
  console.log('wishes man=>', wishes)




  return (
    <html lang="fa" dir="rtl">
      <head>
        <link
          rel="stylesheet"
          href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
          // integrity="sha256-XQoYMqMTK8LvdlxU/3rYK8tG+AA1Z3xX6pH5yXkQ1pU="
          crossOrigin=""
        />
      </head>
      <body>
        <CartProvider>
          <AosInt />
          <Navbar isLogin={user ? true : false} wishes={JSON.parse(JSON.stringify(wishes))} />
          {children}
          <ToastContainer />
          <ScrollToTop /> 
        </CartProvider>
        
      </body>
    </html>
  );
}
